import esbuild from 'esbuild';
import process from 'node:process';
import builtinModules from 'builtin-modules';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

`;

const prod = (process.argv[2] === 'production');

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'@langchain/mistralai',
		'@qdrant/js-client-rest',
		'uuid',
		...builtinModules.filter(m => !/^_/.test(m))
	],
	format: 'cjs',
	target: 'es2020',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outdir: `.`,
	loader: {
		'.ts': 'ts'
	},
	define: {
		global: 'globalThis',
	},
	platform: 'node',
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
